### ISSUE TITLE
W0622: Redefining built-in 'hex'

### ISSUE THREAD

**Issue by ariccio** [dmulholland/hex#1]
Not a big problem, but `pylint` makes a valid point. Maybe `hexdump` or similar would be a better name?

**Comment by dmulholl** [comment]
Not sure I get your meaning - do you mean it shadows a system binary called `hex`? You can rename the file to anything you like if that's the case.

**Comment by ariccio** [comment]
Not a system binary, but the python built-in `hex`. I imagine this could be confusing for someone.
