### ISSUE TITLE
Colorized Output

### ISSUE THREAD

**Issue by 0xflotus** [dmulholland/hex#2]
For personal purposes I [forked](https://github.com/0xflotus/hex2/) this repository and added colorized output inspired by [hex](https://github.com/sitkevij/hex)

Is it possible to bring this feature in the upstream repository?

<img width="831" alt="Bildschirmfoto 2022-01-27 um 11 52 30" src="https://user-images.githubusercontent.com/26602940/151344889-ee0a5160-c782-4894-9b22-58fa2243f112.png">

**Comment by dmulholl** [comment]
Hey, that's really nice looking!

I'm not going to merge the changes, purely because I want to leave this implementation as 'stupidly simple' as possible, but I'll add a link to your fork to the readme for anyone who's looking for something a bit fancier.
